source 'https://github.com/CocoaPods/Specs.git'

target 'MXSegmentedPager', :exclusive => true do
  pod "MXSegmentedPager", :path => "../"
  pod 'CSStickyHeaderFlowLayout'
end

target 'Tests', :exclusive => true do
  pod "MXSegmentedPager", :path => "../"

  
end
